const students = ["Mark", "Denis", "Sasha", "Artem"]
students.push("Nikita")
console.log(students)
console.log(students.length)
console.log(students[7])
students[0] = "Danil"
console.log(students)
students.pop()
students.shift()
console.log(students)
students.splice(2, 1)
console.log(students)
students.forEach((student) => console.log(student))
console.log(students)
let newStudents = students.filter((student) => student[0] == "D")
console.log(newStudents)
students.push("Aleg")
const Students = students.map((student) => student.toLowerCase())
console.log(Students)
Students.sort()
console.log(Students)